In [47]:
# Load the data set Health_Score.csv.

# Predict Birth Rate based on all other related fields


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


data=pd.read_excel("/content/Health_Score.xlsx")

In [48]:
data.head()

,Birth Rate,No of Hospitlas,No of Doctors,Annual Income,Population Density
0,8.0,78,284,9.1,109
1,9.3,68,433,8.7,144
2,7.5,70,739,7.2,113
3,8.9,96,1792,8.9,97
4,10.2,74,477,8.3,206

In [49]:
data.isnull().sum()

Birth Rate            0
No of Hospitlas       0
No of Doctors         0
Annual Income         0
Population Density    0
dtype: int64

In [50]:
x=data.iloc[:,1:].values
y=data.iloc[:,0].values

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=1)
print(x_train.shape,x_test.shape)

(42, 4) (11, 4)

In [52]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

In [53]:
print(r2_score(y_test,y_pred))

-0.599383373530775

In [54]:
df_y_test= pd.DataFrame(y_test, columns = ['Birth Rate'])
df_y_test_pred =  pd.DataFrame(y_pred, columns = ['Prediction'])
df_diff =df_y_test- df_y_test_pred
y_test_pred = pd.concat ([df_y_test, df_y_test_pred ],axis =1)
y_test_pred['Difference'] =df_y_test ['Birth Rate']- df_y_test_pred['Prediction']
print (y_test_pred)

    Birth Rate  Prediction  Difference
0          5.0    8.656548   -3.656548
1          7.5   10.570499   -3.070499
2         10.0    9.129261    0.870739
3          9.8    9.565185    0.234815
4          9.8    9.153972    0.646028
5          9.0   10.197631   -1.197631
6         10.1    9.005799    1.094201
7          9.4   10.365480   -0.965481
8         10.1    7.506332    2.593668
9          9.7    9.203842    0.496157
10         8.5    6.608488    1.891512

In [55]:
y_pred=lr.predict(x)

In [56]:
print(r2_score(y,y_pred))

0.08950585813004241

In [57]:
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.954
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              254.2
Date:                Tue, 07 Apr 2026   Prob (F-statistic):                    4.15e-32
Time:                        14:43:56   Log-Likelihood:                         -112.63
No. Observations:                  53   AIC:                                      233.3
Df Residuals:                      49   BIC:                                      241.1
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0017      0.009      0.184      0.855      -0.017       0.020
x2             0.0014      0.001      1.486      0.144      -0.000       0.003
x3             0.9456      0.137      6.892      0.000       0.670       1.221
x4            -0.0070      0.006     -1.091      0.281      -0.020       0.006
==============================================================================
Omnibus:                        1.186   Durbin-Watson:                   1.675
Prob(Omnibus):                  0.553   Jarque-Bera (JB):                0.537
Skew:                           0.185   Prob(JB):                        0.765
Kurtosis:                       3.325   Cond. No.                         328.
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.